### ISSUE TITLE
not working with build 20.8.301

### ISSUE THREAD

**Issue by guikaercher** [paveyry/better-hangoutschat#15]
Hey, first of all thanks for this theme.
So, the last time GHC updated it's not working for me anymore. I'm at win10. 
The chat windows keeps at a blank window, bug I'm not able to login.
![image](https://user-images.githubusercontent.com/16124687/93203278-8200d080-f72a-11ea-951f-ba021d8aed1e.png)

![image](https://user-images.githubusercontent.com/16124687/93203376-b83e5000-f72a-11ea-82a0-d380d3416d07.png)

**Comment by tvories** [comment]
Looks like the newest chat release isn't compatible.  I am also on `20.8.301` on a Mac and it doesn't work for me now, either.

**Comment by paveyry** [comment]
Release v4.1.3 should fix the issue. It has for me. It seems the plugin won't show the first time you restart GHC after patching, maybe some caching that I'm not aware of. But if you restart it again it should work nicely.
I'll close this issue, but feel free to reopen or create a new one if you still encounter related issues with this new GHC build.

**Comment by tvories** [comment]
I pulled the latest changes and on my Mac tried `THEME=dark make install` and I am still receiving the following error after multiple restarts:

![image](https://user-images.githubusercontent.com/13934524/93355159-fc992100-f7fa-11ea-910d-b32f140d9732.png)

**Comment by paveyry** [comment]
By any chance did `main.js` already contain the patch before you ran `make install`? If you're trying to patch an already patched file, it will break. Either do it on a clean install (but after having run GHC at least once) or just download the pre-patched js file and put it manually without using `make`

**Comment by tvories** [comment]
`main.js` hadn't been touched since my latest re-install.  That being said, I manually patched the `main.js` from the release and that worked fine!  Thanks for the help.

**Comment by t9t** [comment]
It doesn't seem to work for me at all any more, on MacOS with Chat 20.8.301, even after restarting the client. I tried all three themes, but the client just keeps its own layout. When I eg. `diff /Applications/Chat.app/Contents/Resources/app/main.js out/slacktheme/main.js`, it is clear that the files are exactly the same (and when I `diff` against a backup of the original `main.js` there are definitely differences).

So it seems as if Chat doesn't pick up this `main.js` at all...

Edit: what helped for me was to explicitly reload, eg. ⌘R (see also the View menu).

**Comment by paveyry** [comment]
@t9t I'm sorry it took so long, I was not able to replicate that error for a while, but I have now identified it and the latest version (4.1.5) should fix this error.
